### ISSUE TITLE
Error occurred inside the app installation script on armhf architecture (armv7l, Olimex Lime2)

### ISSUE THREAD

**Issue by dankoi** [YunoHost-Apps/writefreely_ynh#102]
### Bug description

The writefreely_ynh installation script fails to finish successfully because of a missing armhf.src file. (The script detects the architecture as armhf)

By copying the file armel.src into armhf.src, immediately after starting the installation script, allows to install writefreely correctly.

### Context

- Hardware and kernel: *Olimex Lime2, Allwinner sun7i (A20) Family, 5.10.0-14-armmp-lpae 1 SMP Debian 5.10.113-1 (2022-04-29) armv7l GNU/Linux*
- YunoHost version: 11.0.6
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: installing the main branch as well as branch testing report the same error

### Steps to reproduce

Just start the package installation through the yunohost web interface.

Launching install of the testing branch (using the command given on your github front page) results with the same error.

### Logs

https://paste.yunohost.org/raw/abibemiwer

**Comment by yalh76** [comment]
armhf.src has been implemented

**Comment by dankoi** [comment]
Great, thanks!

Le 25 septembre 2022 03:08:17 UTC, yalh76 ***@***.***> a écrit :
