### ISSUE TITLE
App is out of date with the upstream

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/writefreely_ynh#2]
Hi
There is new update 0.7.1 for Writefreely.https://github.com/writeas/writefreely/tree/v0.7.1
It would be nice if the app gets this upgrade. :nerd_face:

**Comment by yalh76** [comment]
upgrade done in https://github.com/YunoHost-Apps/writefreely_ynh/tree/v0.7.1

**Comment by yalh76** [comment]
now up to date
