### ISSUE TITLE
Application not compatible with ARM

### ISSUE THREAD

**Issue by yalh76** [YunoHost-Apps/writefreely_ynh#4]
As application not compatible with Arm:
https://github.com/YunoHost-Apps/writefreely_ynh/issues/3
Prevent installing on Arm

**Comment by yalh76** [comment]
waiting for https://ci-apps-arm.yunohost.org/ci/apps/writefreely/ results

**Comment by yalh76** [comment]
It's confirmed that WriteFreely is not available on ARM.
Managed during the installation.

**Comment by yalh76** [comment]
seems to be possible to install writefreely on arm: https://write.as/buttpicker/the-expected-tutorial-how-to-install-writefreely-on-a-raspberry-pi-3-in-10

**Comment by yalh76** [comment]
Built Writefreely for ARM done : https://github.com/YunoHost-Apps/writefreely_ynh/pull/39

**Comment by yalh76** [comment]
Waiting for test results: https://ci-apps-arm.yunohost.org/ci/apps/writefreely/

**Comment by yalh76** [comment]
Writefreely can be installed on arm64

**Comment by VonKavalier** [comment]
Hi, I'm trying to install it on my raspberry 3B+, but I still get the error on install, saying it's not compatible with arm.

I'm using 0.10.0~ynh1 though :/

Here are the logs : https://paste.yunohost.org/raw/gowununefu
