### ISSUE TITLE
Changing Domains Breaks WriteFreely

### ISSUE THREAD

**Issue by tootbrute** [YunoHost-Apps/writefreely_ynh#46]
**Problem:**
Right now there is no way to change your host (Mastodon domain) in App Configuration. Also changing domain names breaks all post links. All my links seem hard-coded to the old domain. Blog.arkadi.one works fine but every post on that page links back to old domain.

I run WriteFreely on my Yunohost server. When I first started, I had a blog.arkadi.nohost.me  domain, but recently changed to my own domain.tld -> blog.arkadi.one

It seems federation is first setup automatically but there is no way to change it later. I tried editing the config.ini file but the value for host is __DOMAIN NAME__ and it takes this from settings.yml. It's already the correct value. Nevertheless, I tried changing the config.ini and restarting writefreely, it still didn't work.

Maybe this is an Nginx issue?

The only way I think I can fix this is to reinstall WriteFreely but then I will lose all my posts because there isn't a way to import old posts via csv, zip, or json (or is there?)

**Comment by yalh76** [comment]
Hi @tootbrute 

I think, I found the issue.

In the config.ini file L24: `host              = https://blog.arkadi.one`
instead of `host              =https://blog.arkadi.one`
the space between `=` and `http` seems important

I will fix in in the change_url script

**Comment by tootbrute** [comment]
config.ini seems to have a space there but it refers to a variable it think it gets from settings.yml in previous directory
`[app]
site_name         = WriteFreely
site_description  = WriteFreely_Blogs
host              = __DOMAIN_URL__
theme             = write
disable_js        = false
webfonts          = true
single_user       = __SINGLEUSER__
`
so i went to settings.yml and changed domain: it previously said "blog.arkadi.one", i changed it to "https://blog.arkadi.one"

`db_name: writefreely
domain: https://blog.arkadi.one
final_path: /var/www/writefreely
id: writefreely
install_time: 1548900515
`
i did $ yunohost service restart_or_reload writefreely
and the same for nginx

no change. still federates with arkadi.nohost.me and all my links point to arkadi.nohost.me BUT if i change the link to arkadi.one the links work. this must be related to my problem

https://blog.arkadi.nohost.me//want-by-cindy-pon (doesn't work!) but if i change the URL to https://blog.arkadi.one/want-by-cindy-pon it works.

**Comment by tootbrute** [comment]
OK we may be talking about different config.ini file

previous changes I made were to 
/etc/yunohost/apps/writefreely/conf/confi.ini

i just found /var/www/writefreely/config.ini and it has the wrong domain in here...

i changed, reloaded writefreely and now EVERYTHING works.

wow. thanks for the help.

**Comment by yalh76** [comment]
Cool  ^^ and sorry to haven't directly said it was/var/www/writefreely/config.ini

Maybe better you rollback the changes you made in the settings.yml or /etc/yunohost/apps/writefreely/conf/confi.ini
