### ISSUE TITLE
Failed to post

### ISSUE THREAD

**Issue by rushsteve1** [YunoHost-Apps/writefreely_ynh#62]
As of the update a few days ago attempting to post, to drafts or to public, causes a `Failed to post. Please try again.` alert.

The POST request to `/api/posts` responds with a `401` code and the response is:
```json
{"code":401,"error_msg":"Not logged in."}
```

If this is an upstream bug let me known and I will post it there. I will provide more info if needed.

**Comment by yalh76** [comment]
Hi @rushsteve1,
Seems more a bug of the upstream app, maybe it will be better you check their issues.

**Comment by decentral1se** [comment]
More information would be useful! If you create an upstream ticket, please link it here :+1:

**Comment by rushsteve1** [comment]
The issue has mysteriously gone away so I'm gonna close this.
