### ISSUE TITLE
Failed to post / SSO error

### ISSUE THREAD

**Issue by nztvar** [YunoHost-Apps/writefreely_ynh#73]
Problem:
New install, either open or closed, on RPi3B+ fails to save posts. Issue appears to be related to SSO.

Request headers:
```
Host: parlevent.saewyc.org
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0 PureBrowser/60.9.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://parlevent.saewyc.org/
Content-type: application/json
Content-Length: 84
Cookie: SSOwAuthUser=amgine; SSOwAuthHash=cddfec4faecf2e1a2502c72f40d9ccac02cf75cfe2889058a30ce819778d890c6b9f9ffaa646ad3d63353cc7acf8270199a7e44ecd8f8067533be8a6d10e1530; SSOwAuthExpire=1580687991.54; wfu=MTU4MDEwMjY4MXxIM2JtTUNMaEJpYmxicHpLT3JpdkFoMTFNQllTYkV0TFFjWE5hN3NydzNsSWxLbktRbWlUUEFEZ3A1dGRtd1J1aDY0czg5RHRVS1hFWWppcFBUUTcxcWhKMW1wel9lakVMdDc0LUYzSnJxNDV6UzUtMy1vd212b2hKbU1WQ2E4bDVhWkxSR3ZtN1g1WHhVd2ZOVVVPV2dlOERVMnpsQ1VfdzJ1OGxiOTU5eGhqVmNHM2NKWGxFQ2VZMmdkU2dGWGdUSHVBTUxjTWxSTXVTSzg3clRneHRhbGg2R2dNX294eUxCWnBqQjdyTWx3N0g2U2NfN2FreGdmemdqVmxWaGlNa3hLZW5rU1d3TmdrYkpMbGxDUTJBdnBxUkIxdE5Xc191eFZRQk1nOFJ5WFoxVWo0RkxKZkxJS2E1WHRoamtKeTdCMkxRbnNBS2RyY3BySTB2bnVianNaT09USjRKMFpscGhfR2dDUW9GdWYzOFFTVDYxY2J0TW1IYmRHWkFDLVJ1cm83N2YwVF9ZeHJLaC1LR2pBZE92RXo0LU9tVWo5RHJfZks4OTBmVEItNmJrM2h5Tk92fAuAIw0OG_kRG4plxVnhXCZmzSmQNbvEPDpNVX4hTu2M
DNT: 1
Connection: keep-alive
```

Response headers:
```
HTTP/2.0 401 Unauthorized
server: nginx/1.14.2
date: Mon, 27 Jan 2020 05:25:06 GMT
content-type: application/json; charset=UTF-8
content-length: 41
x-sso-wat: You've just been SSOed
set-cookie: SSOwAuthRedirect=;; Path=/yunohost/sso/; Expires=Thu, 01 Jan 1970 00:00:00 UTC; Secure; HttpOnly; SameSite=Lax ;;
content-security-policy: upgrade-insecure-requests
content-security-policy-report-only: default-src https: data: 'unsafe-inline' 'unsafe-eval'
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
x-download-options: noopen
x-permitted-cross-domain-policies: none
x-frame-options: SAMEORIGIN
X-Firefox-Spdy: h2
```

**Comment by yalh76** [comment]
Well... It seems its related to https://github.com/YunoHost/issues/issues/1420
And you have that issue because you installed writefreely as private.
Until the issue is solved, it would be better to install writefreely as a public application

**Comment by nztvar** [comment]
Thanks for the issue link!

I tried installing Writefreely more than 6 times, with slight variations to the install, both public and private, single user and multi. It is currently uninstalled as it is not usable.

**Comment by yalh76** [comment]
Ok then, I close that issue

**Comment by ahstro** [comment]
Why did you close this? Didn't sound like it was resolved for @nztvar, and it's broken for me too ☹️

**Comment by yalh76** [comment]
> 
> 
> Why did you close this? Didn't sound like it was resolved for @nztvar, and it's broken for me too ☹️

@nztvar abandoned the installation of writefreely_ynh, so without any logs, any information, I wasn"t able to do any diagnosis.

So if you can explain what is your problem and if different from this one, create a new issue

**Comment by nztvar** [comment]
Hello!

Well, when you were informed that I had tried every installation method, private and public, you did not ask further questions either.

@ahstro: my installation hardware is an RPi 3B+, which is 32bit running ynh's deb 9 image. 32bit appears to be receiving less attention. My working assumption is ssowat has issues on 32bit platforms, and they will not be fixed in the near future.

**Comment by ahstro** [comment]
@nztvar Hmm, my setup is 64-bit, and since the problems seem similar, I'm guessing that's not the reason. I rebooted my server and it started working again, so at least the issue wasn't permanent.

**Comment by nztvar** [comment]
<hmms> That is actually something I had not tried. I will see if I can this weekend.

**Comment by yalh76** [comment]
ok then, I let you test and if is the problem is still here, we will reopen the issue

**Comment by katomaso** [comment]
Hi, I have the same problem. Installed on RaspberryPi with settings: public, single user instance. 
When I try to publish a new post, I get the same reply as all the others here:

**status**: 401
**x-sso-wat**: You've just been SSOed

**Comment by yalh76** [comment]
Have you tried to logoff YunoHost first ?

**Comment by katomaso** [comment]
Accessing writefreely from a different browser than that I use for Yunohost administration worked. I was able to POST posts. Actually even after logging in to Yunohost, I could still post in writefreely.

**Comment by yalh76** [comment]
maybe it's related to https://github.com/YunoHost/issues/issues/1420
But you should have the issue each time you are connected to the YunoHost part...

**Comment by katomaso** [comment]
I think I have found a way how to reproduce the issue
- add new domain to be managed by ynh
- go to that domain and authenticate to ynh
- install writefreely and use the domain as the target one
- after installation, go to your new writefreely instance and try to post an article - this will fail

After you remove all cookies/app data for the domain, you will be able to post articles again.

**Comment by yalh76** [comment]
ok then, seems really https://github.com/YunoHost/issues/issues/1420

There is ongoing PR to solve that at YunoHost level

**Comment by deckname** [comment]
Same issue here, not installed as private. I agree that it's an issue with yunohost login. Logged out it works, being logged in it doesn't work.

**Comment by hieronymousch** [comment]
Same issue here on public instance...  As LDAP is not working and accounts are made seperatly, I just disabled the SSO in nginx (just like with Bitwarden)
